### ISSUE TITLE
[Hazard] Revive Kill Sniper temporarily disabled

### ISSUE THREAD

**Issue by SteffanLong** [SteffanLong/DestinyTrialsReport#1]

**Comment by v-fedorov** [comment]
so we can either multiply (impact * attack) and find some kind of average value to check against for the revive snipes.
orrrrrr just match it against an array of the names/nodesHash

**Comment by SteffanLong** [comment]
Is that how the game calculates damage? Impact * Attack? I believe I heard someone say 300 damage is enough to one hit kill a revive.

**Comment by v-fedorov** [comment]
Im not sure how the game does it, id assume its something similar. next trials ill test it out
