### ISSUE TITLE
Double Grenade tag does not appear when using Starfire Protocol and Fusion Grenade on sunsinger

### ISSUE THREAD

**Issue by RubidiumBlade** [SteffanLong/DestinyTrialsReport#19]
title, I looked myself up to test the website and saw that the tag didn't appear even though I knew it should have. I don't have gift of the sun equipped, which I would assume to be the problem, but the Starfire Protocol grants another grenade when using the fusions.

**Comment by SteffanLong** [comment]
Thanks for this find. This will be fixed quickly.

**Comment by SteffanLong** [comment]
fixed in 414bee7
