### ISSUE TITLE
[Request] Permalink to guardian's report

### ISSUE THREAD

**Issue by kunalbhat** [SteffanLong/DestinyTrialsReport#28]
A feature request for a shareable URL with a query string that pre-populates and kicks off a search for a specific guardian/gamertag.

e.g. `http://www.destinytrialsreport.com/?g=<gamertag>&p=<platform>`

And maybe a small url icon for copy and paste purposes. Example UI:

<img width="801" alt="screen shot 2015-07-22 at 5 00 43 pm" src="https://cloud.githubusercontent.com/assets/755630/8838592/520c13e8-3093-11e5-9563-96d1f902efed.png">

**Comment by kunalbhat** [comment]
Or perhaps e.g. `http://www.destinytrialsreport.com/<platform>/<gamertag>` is better, and matches the format used at `destinytracker.com`

**Comment by SteffanLong** [comment]
Thanks for the suggestion, we will certainly implement this.

**Comment by v-fedorov** [comment]
just pushed this up, the button is having some issues on mobile so i had to hide it for now.
`http://www.destinytrialsreport.com/ps/gamertag` and `http://www.destinytrialsreport.com/xbox/gamertag`

maybe eventually add support to include all 3 names

**Comment by kunalbhat** [comment]
Nice! Only thing I noticed is that it appears the logic determining platform for the permalink isn't correct, as when I am search for an Xbox gamertag and then hit copy, the URL that is generated has `/ps` in it.

p.s. I want to help, but not very familiar with Angular. ;)

**Comment by kunalbhat** [comment]
Not necessarily the logic, but perhaps instead what is getting passed to the copy+paste plugin.

**Comment by v-fedorov** [comment]
good call, i just pushed up a fix, let me know if it works

**Comment by v-fedorov** [comment]
ok its fixed
