### ISSUE TITLE
[Last Match] Medals do not align properly

### ISSUE THREAD

**Issue by SteffanLong** [SteffanLong/DestinyTrialsReport#6]
![dtr medals wrapping to newline](https://cloud.githubusercontent.com/assets/5157291/8755090/2d73029a-2c7d-11e5-8edc-d778206b4e9d.png)

**Comment by kunalbhat** [comment]
This is happening when some medal title takes up 2 lines of text. 

Using inspector, I can force that state, here is the comparison:

![screen shot 2015-07-21 at 1 14 40 pm](https://cloud.githubusercontent.com/assets/755630/8809024/a5d1d37a-2fab-11e5-809c-09e64ee02220.png)

![screen shot 2015-07-21 at 1 22 01 pm](https://cloud.githubusercontent.com/assets/755630/8809023/a5d1b066-2fab-11e5-87b5-0528571ddddc.png)

This problem will happen with floating columns of various heights. Things like [Isotope's 'fitRows'](http://isotope.metafizzy.co/layout-modes.html) option address this issue. But that introduces a whole library to fix the problem... the simplest way to fix this would be to give those medal columns a class and a specify a height, maybe one that supports three lines of text and hide overflow.

**Comment by SteffanLong** [comment]
Thank you for the update.

**Comment by SteffanLong** [comment]
fixed in 99ff64d
