### ISSUE TITLE
Tooltip at top should be moved to left or right. Tooltip collides with top of screen

### ISSUE THREAD

**Issue by andrewlube** [SteffanLong/DestinyTrialsReport#77]
Hey bud,

When hovering over a user, you have access to see what perks they have equipped to their character. The top skills, when you hover over will have the tooltip colliding with the top. Either you should use line breaks in your tooltip, or move it to left or right.

FireFox.

**Comment by SteffanLong** [comment]
This issue has been fixed in our redesign that we will be releasing soon.
