### ISSUE TITLE
Learn who your opponent is

### ISSUE THREAD

**Issue by Macarse** [SteffanLong/DestinyTrialsReport#96]
@SteffanLong Do you know if there is an API to know who you are against in trials?
I would like to know if there is a way to search for my username and get my opponents.

Thanks!

**Comment by v-fedorov** [comment]
There is no way to get your opponents based on username, you would have to call the PostGameCarnage endpoint for each match you have played to get any detail about the fireteam

**Comment by v-fedorov** [comment]
There is no way to get your opponents based on username, you would have to call the PostGameCarnage endpoint for each match you have played to get any detail about the fireteam

**Comment by Macarse** [comment]
@v-fedorov Thanks.
